version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies for UI Tests
          command: |
            cd ui-tests
            npm install
      - run:
          name: Run Nightwatch Tests
          command: |
            cd ui-tests
            npx nightwatch

  api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies for API Tests
          command: |
            cd api-tests
            npm install
      - run:
          name: Run Supertest Tests
          command: |
            cd api-tests
            npx jest

workflows:
  version: 2
  test:
    jobs:
      - ui-tests
      - api-tests
